strategy: LongCallStrat
fixed_params:
  stop_loss_pct: 100
  open_time: "09:30"
  close_time: "16:00"
range_params:
  pct_otm:
    start: -1.0
    end: 1.0
    step: 0.02
  profit_target_pct:
    start: 5
    end: 400
    step: 5
backtest:
  days: 90